name: linux builds

on:
  push:
    branches: [ "master", "github_actions" ]
  pull_request:
    branches: [ "master" ]

env:
  GODOT_BASE_BRANCH: "4.3"

#this will cancel other running actions with the same yml
#helps lessen running actions and prevents action duplicates
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "ubuntu-20.04"
    name: ${{matrix.name}}


    strategy:
      matrix:
        include:
          - name: 4.3 Editor
            precision: single
            target: editor
            arch: x86_64

          - name: 4.3 Template
            precision: single
            target: template_release
            arch: x86_64


            #32-bit
          - name: 4.3 Editor
            precision: single
            target: editor
            arch: x86_32

          - name: 4.3 Template
            precision: single
            target: template_release
            arch: x86_32






    steps:
        #setup jdk 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      #setup this repo
      - uses: actions/checkout@v2



      # Setup custom buildroot so we may use an old but compatible GLIBC version, while keeping recent toolchain.
      # This allows to make production builds that are compatible with older Linux distros.
      # TODO Enhancement: cache buildroot so future runs can use it?
      # TODO Enhancement: make buildroot setup a self-contained step. There are bits of setup elsewhere.
      #      Currently I also setup `PATH` in the Compilation step because modifications
      #      do not persist between steps (?). I also placed this step after checkout because the checkout step changes
      #      the working directory for all following steps.
      - name: Setup buildroot
        run: |
          wget https://download.tuxfamily.org/godotengine/toolchains/linux/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar -xjf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          cd x86_64-godot-linux-gnu_sdk-buildroot
          ./relocate-sdk.sh
          cd ..


#this is probably the cause of compilation errors
#maybe theres's api changes that prevents it to compile
      # Clone GodotCPP
#      - uses: actions/checkout@v2
#        with:
#          repository: godotengine/godot-cpp
#          ref: ${{env.GODOT_BASE_BRANCH}}
#          path: godot-cpp


      - name: git submodule update
        run: git submodule update --init


       #install libraries for 32-bit
      - name: install 32-bit libs
        if: ${{ matrix.arch == 'x86_32' }}
        run: sudo apt install -y libc6-dev-i386

       #compile with scons
      - name: Compilation
        run: |
          PATH=${GITHUB_WORKSPACE}/x86_64-godot-linux-gnu_sdk-buildroot/bin:$PATH
          scons verbose=yes platform=linux tests=no dev_build=no target=${{matrix.target}} precision=${{matrix.precision}} arch=${{matrix.arch}}


      #list all folders and subdirectories since I don't know which folder to upload
      - name: list files
        run: ls -ash *

      #upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: hoodie-${{matrix.target}}-${{matrix.arch}}-linux
          path: demo/bin/*
